export const names: string[] = [
  "Quizzekatt",
  "Quizter Sjögren",
  "Quiztina Aguilera",
  "Quiz Brown",
  "Quiz Medina",
  "Ernst Quizteiger",
  "Quiztian Luuk",
  "Quiztoffer Robinson",
  "Quiztarina den Store",
  "Quizopatra",
  "Napoleon Quizoparte",
  "Quiztiano Ronaldo",
  "Quizius Ceasar",
  "Quizling",
  "Carola HäggQuizt",
  "Jesus Quiztus",
];
